---
- hostname: name={{ hostname }}

- name: add mongo user
  user: name={{ mongouser }} comment="mongouser" password={{ mongouserpwd |password_hash('sha512') }} update_password=always

- name: copy rc.d template
  template: src=rc.local.j2 dest=/etc/rc.d/rc.local mode=644

- name: mk bin dir
  file: path={{ mongohome }} state=directory mode=0755 owner={{ mongouser }} group={{ mongouser }}

- name: getbin
  unarchive: src={{ getbinurl }} dest={{ mongohome }} remote_src=yes owner={{ mongouser }} group={{ mongouser }}

- name: add the path in the bashrc files
  lineinfile: dest=/etc/bashrc line='export PATH=$PATH:{{ mongohome }}' insertafter='EOF'  state=present

- name: Generate /etc/hosts file
  template:  src=hosts.j2 dest=/etc/hosts backup=yes
...
