---
# defaults file for mongod
maxmem: 4
#mongod主节点最大使用内存
#maxmem2: '{{ maxmem/2 }}'
##这个必须加单引号括起来
replmaxmem: '{{ maxmem/2 }}'
authorization: disabled
#是否启用用户验证
primarydata: '{{ dbhome }}/{{ primary }}'
#主节点存放数据位置
seconddata: '{{ dbhome }}/{{ second }}'
#从节点存放数据位置
arbitratordata: '{{ dbhome }}/{{ arbitrator }}'
#仲裁节点存放数据位置
primaryport: 27019
#复制集主端口
secondport: 27020
#复制集从端口
arbitratorport: 27021
#仲裁节点端口
